<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Delete' => '',
    'Employees' => '',
    'ID' => '',
    'Positions' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Employee: {name}' => '',
    'Воскресенье' => '',
    'Вторник' => '',
    'ГОБМП' => '',
    'График работы врачей' => '',
    'Добавить' => '',
    'Добавлено в' => '',
    'Должности' => '',
    'Должность' => '',
    'Кабинет' => '',
    'Кодекс здоровья' => '',
    'На главную страницу' => '',
    'Назад' => '',
    'Название' => '',
    'Нормативные правовые акты' => '',
    'О нас' => '',
    'ОСМС' => '',
    'Обновить' => '',
    'Обновить: {name}' => '',
    'Обновлено в' => '',
    'Перечень социально значимых заболеваний' => '',
    'Платные услуги' => '',
    'Позиция' => '',
    'Полное имя' => '',
    'Понидельник' => '',
    'Правил оказания стационарной помощи' => '',
    'Правила оказания скорой медицинской помощи' => '',
    'Правила прикрепления к организациям  ПМСП' => '',
    'Проф.осмотр' => '',
    'Пятница' => '',
    'Работники' => '',
    'Рисунок' => '',
    'Руководство' => '',
    'Служба поддержки пациентов' => '',
    'Сохранить' => '',
    'Среда' => '',
    'Суббота' => '',
    'Территория обслуживания поликлиники' => '',
    'Четверг' => '',
];
