<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Delete' => '',
    'Employees' => '',
    'ID' => '',
    'Positions' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Employee: {name}' => '',
    'Администрация' => '',
    'Введите имя пациента' => '',
    'Воскресенье' => '',
    'Вторник' => '',
    'Выписан' => '',
    'ГКП на ПХВ "Областной противотуберкулезный диспансер"' => '',
    'ГОБМП' => '',
    'Госпитализирован' => '',
    'Посмотреть график работы и оценить врача' => '',
    'Дата обращение' => '',
    'Добавить' => '',
    'Добавлено в' => '',
    'Должности' => '',
    'Должность' => '',
    'ИИН пациента' => 'Науқастың ЖСН',
    'Искать' => '',
    'История' => '',
    'История ОПТД' => '',
    'Кабинет' => '',
    'Кодекс здоровья' => '',
    'Комментарий' => '',
    'На главную страницу' => '',
    'Назад' => '',
    'Название' => '',
    'Наши услуги' => '',
    'Неотложеный' => '',
    'ОСМС' => '',
    'Обновить' => '',
    'Обновить: {name}' => '',
    'Обновлено в' => '',
    'Отделение' => '',
    'Отказ от госпитализации' => '',
    'Отправить' => '',
    'Оценка' => '',
    'Палата' => '',
    'Список госпитализированных' => '',
    'Переведен' => '',
    'Перечень социально значимых заболеваний' => '',
    'Плановый' => '',
    'Позиция' => '',
    'Полное имя' => '',
    'Понидельник' => '',
    'Правил оказания стационарной помощи' => '',
    'Правила оказания скорой медицинской помощи' => '',
    'Проф.осмотр' => '',
    'Пятница' => '',
    'Работники' => '',
    'Рисунок' => '',
    'Сердце' => '',
    'Сохранить' => '',
    'Среда' => '',
    'Статус' => '',
    'Суббота' => '',
    'Тарихы' => '',
    'Тип' => '',
    'Ф.И.О пациента' => '',
    'Четверг' => '',
    'Экстренный' => '',
	'Просто ужасно' => '',
	'Очень плохо' => '',
	'Плохо' => '',
	'Удовлетворительно' => '',
	'Хорошо' => '',
	'Отлично' => ''
];
