<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Delete' => '',
    'Employees' => '',
    'ID' => '',
    'Positions' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Employee: {name}' => '',
    'Воскресенье' => 'Жексенбі',
    'Вторник' => 'Сейсенбі',
    'ГОБМП' => 'Тегін медициналық көмектің кепілдік берілген көлемінің тізбесін бекіту туралы',
    'График работы врачей' => 'Дәрігерлердің жұмыс уақыты',
    'Добавить' => 'Қосу',
    'Добавлено в' => '',
    'Должности' => '',
    'Должность' => '',
    'Кабинет' => 'Кабинеті',
    'Кодекс здоровья' => 'Денсаулық кодексі',
    'На главную страницу' => 'Басты бетке өту',
    'Назад' => 'Кері қайту',
    'Название' => 'Атауы',
    'Нормативные правовые акты' => 'Нормативтік құқықтық актілер',
    'О нас' => 'Біз туралы',
    'ОСМС' => 'МӘМС',
    'Обновить' => '',
    'Обновить: {name}' => '',
    'Обновлено в' => '',
    'Перечень социально значимых заболеваний' => 'Әлеуметтік мәні бар аурулардың және айналадағылар үшін қауіп төндіретін аурулардың тізбесін бекіту туралы',
    'Платные услуги' => 'Ақылы қызметтер',
    'Позиция' => '',
    'Полное имя' => 'Толық аты-жөні',
    'Понидельник' => 'Дүйсенбі',
    'Правил оказания стационарной помощи' => 'Стационарды алмастыратын көмек',
    'Правила оказания скорой медицинской помощи' => 'Жедел медициналық көмек көрсету қағидалары',
    'Правила прикрепления к организациям  ПМСП' => 'МҰ бекіту қағидалары туралы',
    'Проф.осмотр' => 'Профилактикалық медициналық тексеріп-қарауды',
    'Пятница' => 'Жұма',
    'Работники' => '',
    'Рисунок' => '',
    'Руководство' => 'Басқарма',
    'Служба поддержки пациентов' => 'Науқастарға қолдау көрсету қызметі',
    'Сохранить' => 'Сақтау',
    'Среда' => 'Сәрсенбі',
    'Суббота' => 'Сенбі',
    'Территория обслуживания поликлиники' => 'Емхананың қызмет көрсету аймағы',
    'Четверг' => 'Бейсенбі',
];
